<a href="https://colab.research.google.com/github/gaeun120312/Deeplearning/blob/main/17_%EC%9E%90%EC%97%B0%EC%96%B4_%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

from tensorflow.keras.preprocessing.text import text_to_word_sequence

text = '해보지 않으면 해낼 수 없다'

# 토큰화
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
# 단어 빈도 세기
# 전처리 위한 3개 문장 정하기
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

# 토큰화 함수 지정
token = Tokenizer()

# 토큰화 함수에 문장 적용
token.fit_on_texts(docs)

In [5]:
# 단어 빈도수 계산
print('단어 빈도수 계산: ', token.word_counts)

단어 빈도수 계산:  OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [6]:
# 문장 카운트 계산
print('문장 카운트: ', token.document_count)

문장 카운트:  3


In [7]:
print('각 단어가 몇 개의 문장에 포함되어 있는가: ', token.word_docs)

각 단어가 몇 개의 문장에 포함되어 있는가:  defaultdict(<class 'int'>, {'텍스트의': 2, '나누어': 1, '먼저': 1, '토큰화합니다': 1, '각': 1, '단어를': 1, '인식됩니다': 1, '단어로': 1, '토큰화해야': 1, '딥러닝에서': 2, '사용할': 1, '있습니다': 1, '결과는': 1, '토큰화한': 1, '수': 1})


In [8]:
print('각 단어에 매겨진 index 값: ', token.word_index)

각 단어에 매겨진 index 값:  {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [9]:
# 단어 원-핫 인코딩
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [10]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [11]:
from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [12]:
# 단어 임베딩
from tensorflow.keras.layers import Embedding, Dense, Flatten
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(16, 4))

In [22]:
# 텍스트의 감정 분석(긍정, 부정)
import numpy as np

docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.',
        '한 번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요',
        '연기가 어색해요', '재미없어요']

# 감성사전 (긍정:1, 부정:0)
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [14]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [15]:
x1 = token.texts_to_sequences(docs)
print("토큰화 결과: ", x1)

토큰화 결과:  [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 서로 다른 길이의 데이터를 4로 맞추기
padded_x = pad_sequences(x1, 4)
print("패딩 결과: ", padded_x)

패딩 결과:  [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [17]:
from collections.abc import Sequence

# 임베딩에 입력된 단어 수 지정
word_size = len(token.word_index) + 1
word_size

22

In [23]:
# 모델 생성
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 4, 8)              176       
                                                                 
 flatten_3 (Flatten)         (None, 32)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 209 (836.00 Byte)
Trainable params: 209 (836.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 0.6955 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 16ms/step - loss: 0.6934 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 16ms/step - loss: 0.6913 - accuracy